<?php

use Drupal\Core\Form\FormStateInterface;

function keepincrm_form_alter(&$form, FormStateInterface $form_state, $form_id) {              
if (stripos($form_id, "choose_class") !== false || 
    stripos($form_id, "choose_course") !== false || 
    stripos($form_id, "order_service") !== false) {
     $form['#submit'][] = process_form_data($form, $form_state, $form_id);
   }
}

function process_form_data(&$form, FormStateInterface $form_state, $form_id) {
  $base_url = 'https://api.keepincrm.com/v1';
  $data = $form_state->getUserInput();

if (!empty($form_state->getUserInput()) &&
  isset($data['first_name']) && !empty($data['first_name']) && 
  isset($data['contact']['email'], $data['contact']['phone']) && 
  !empty($data['contact']['email']) && 
  !empty($data['contact']['phone']) && 
  (isset($data['class']) && !empty($data['class']) || 
   isset($data['course']) && !empty($data['course']) || 
   isset($data['service']) && !empty($data['service']))) {

$founded_product = null;
$founded_clients = null;
$client_id = "";
$funnel = 2;
$title = "Заявка з сайту";

if ($form['#webform_id'] === "choose_class" && isset($data['class'])) {
  $title = $data['class'];
  $funnel = 2;
}

if ($form['#webform_id'] === "choose_course" && isset($data['course'])) {
  $title = $data['course'];
  $funnel = 2;
}

if ($form['#webform_id'] === "order_service" && isset($data['service'])) {
  $title = $data['service'];
  $funnel = 7;
}

$clients = get_data_from_crm($base_url, '/clients');

if (count($clients) > 0) {
  foreach ($clients as $client) {
    if (strtoupper($client['person']) === strtoupper($data['last_name'] . ' ' . $data['first_name'])) {
        if (in_array($data['contact']['phone'], $client['phones'])) {
            if (in_array($data['contact']['email'], $client['emails'])) {
                $founded_clients[] = $client;
            }
        }
    }
}  
}

if ($founded_clients) {
   $client_id = $founded_clients[0]['id'];
}

$products = get_data_from_crm($base_url, '/materials');

     foreach ($products as $item) {
        if (isset($item['title']) && strtoupper($item['title']) === strtoupper($title)) {
            $founded_product = $item;
	    break;
        }
    }

$crm_data = [ 
    'title' => $title . ' ' . date('m.Y'),
    'source_id' => 6,
    'funnel_id' => $funnel,
    'comment' => $data['notes'],
    'main_responsible_id' => 1,
];

if (isset($client_id) && !empty($client_id)) {
    $crm_data['client_id'] = $client_id;
} else {
    $crm_data['client_attributes'] = [
        'status_id' => 6,
        'company' => isset($data['contact']['company']) ? $data['contact']['company'] : $data['last_name'] . ' ' . $data['first_name'],
        'person' => $data['last_name'] . ' ' . $data['first_name'],
        'email' => $data['contact']['email'],
        'phones' => [
            $data['contact']['phone'],
        ],
    ];
}

if ($founded_product) {
    $crm_data['jobs_attributes'] = [
     [
      'amount' => 1,
      'title' => $founded_product['title'],
      'product_attributes'=> [
        'sku' => $founded_product['sku'],
        'title' => $founded_product['title'],
        'price' => floatval($founded_product['price']),
        'currency' => $founded_product['currency'],
      ]
    ]
    ];
}
  $response = send_data_to_crm($crm_data, $base_url, '/agreements');
}
}

function send_data_to_crm($crm_data, $base_url, $endpoint) {
  $form_data = json_encode($crm_data);
  $url = $base_url . $endpoint;
  try {
    $ch = curl_init($url);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
    curl_setopt($ch, CURLOPT_HTTPHEADER, [
    'Content-Type: application/json',
    'X-Auth-Token: ghwYj9NtXjyVYisKHTsYnhJq' 
    ]);
    curl_setopt($ch, CURLOPT_POST, true);
    curl_setopt($ch, CURLOPT_POSTFIELDS, $form_data);

    $response = curl_exec($ch);
    curl_close($ch);

    return $response;
  } catch (\Exception $e) {
   watchdog_exception('keepeng_integration', $e);
    return FALSE;
  }
}

function get_data_from_crm($base_url, $endpoint) {
  $data = [];
  $page = 1;
  $total_pages = 1;
  
  while ($page <= $total_pages) {
  try {
    $ch = curl_init("$base_url$endpoint?page=$page");
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
    curl_setopt($ch, CURLOPT_HTTPHEADER, [
    'Content-Type: application/json',
    'X-Auth-Token: ghwYj9NtXjyVYisKHTsYnhJq' 
    ]);
    $resp = curl_exec($ch);
    if ($resp === false) {
      throw new Exception(curl_error($ch));
    }
    $response = json_decode($resp, true);
    curl_close($ch);

    if (isset($response['items']) && isset($response['pagination']['total_pages'])) {
      $data = array_merge($data, $response['items']);
      $total_pages = $response['pagination']['total_pages'];
      $page++;
    } else {
      throw new \Exception('Invalid response format');
    }
  } catch (\Exception $e) {
   watchdog_exception('keepeng_integration', $e);
   return $data;
//    return FALSE;
  }
}
   return $data;
}